"use client";

import { useEffect, useState } from "react";
import { getAuthHeaders } from "../../../services/authService";

export default function RecommendationsPage() {
  const [recommendations, setRecommendations] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        const response = await fetch(
  "http://localhost:5000/api/recommendations/history",
  {
    headers: getAuthHeaders()
  }
);

        const result = await response.json();
        console.log("Recommendation API response:", result);

        if (result.success) {
          setRecommendations(result.data);
        }
      } catch (error) {
        console.error(
          "Failed to fetch recommendation history:",
          error
        );
      } finally {
        setLoading(false);
      }
    };

    fetchRecommendations();
  }, []);

  const filteredRecommendations = recommendations.filter(
    (recommendation) => {
      const search = searchTerm.toLowerCase();

      return (
        String(recommendation.recommendation_id)
          .toLowerCase()
          .includes(search) ||
        recommendation.location_name
          ?.toLowerCase()
          .includes(search) ||
        recommendation.crop_name
          ?.toLowerCase()
          .includes(search) ||
        recommendation.compatibility_level
          ?.toLowerCase()
          .includes(search) ||
        recommendation.full_name
          ?.toLowerCase()
          .includes(search)
      );
    }
  );

  return (
    <main style={styles.page}>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <h1 style={styles.title}>
            Recommendations
          </h1>

          <p style={styles.subtitle}>
            Monitor crop recommendations generated by the
            compatibility engine.
          </p>
        </div>
      </div>

      {/* Summary Cards */}
      <div style={styles.summaryCards}>
        <div style={styles.summaryCard}>
          <p style={styles.summaryLabel}>
            Recommendation Engine
          </p>

          <h2 style={styles.summaryNumber}>
            Active
          </h2>

          <p style={styles.summaryDescription}>
            Compatibility engine is available
          </p>
        </div>

        <div style={styles.summaryCard}>
          <p style={styles.summaryLabel}>
            Factors Used
          </p>

          <h2 style={styles.summaryNumber}>
            7
          </h2>

          <p style={styles.summaryDescription}>
            Soil, water, sunlight, environment,
            weather, season, and location
          </p>
        </div>

        <div style={styles.summaryCard}>
          <p style={styles.summaryLabel}>
            Recommendation Records
          </p>

          <h2 style={styles.summaryNumber}>
            {loading ? "..." : recommendations.length}
          </h2>

          <p style={styles.summaryDescription}>
            Saved recommendation history
          </p>
        </div>
      </div>

      {/* Recommendation Table */}
      <section style={styles.tableContainer}>
        <div style={styles.tableHeader}>
          <div>
            <h2 style={styles.sectionTitle}>
              Recommendation Results
            </h2>

            <p style={styles.tableDescription}>
              Recommendation history generated by the compatibility engine.
            </p>
          </div>

          <input
            type="text"
            placeholder="Search recommendations..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={styles.search}
          />
        </div>

        <div style={styles.tableWrapper}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>ID</th>
                <th style={styles.th}>User</th>
                <th style={styles.th}>Location</th>
                <th style={styles.th}>Crop</th>
                <th style={styles.th}>Compatibility Score</th>
                <th style={styles.th}>Classification</th>
                <th style={styles.th}>Date</th>
              </tr>
            </thead>

            <tbody>
              {loading ? (
                <tr>
                  <td
                    colSpan="7"
                    style={styles.emptyMessage}
                  >
                    Loading recommendation history...
                  </td>
                </tr>
              ) : filteredRecommendations.length === 0 ? (
                <tr>
                  <td
                    colSpan="7"
                    style={styles.emptyMessage}
                  >
                    No recommendations found.
                  </td>
                </tr>
              ) : (
                filteredRecommendations.map(
                  (recommendation) => (
                    <tr
                      key={
                        recommendation.recommendation_id
                      }
                    >
                      <td style={styles.td}>
                        {recommendation.recommendation_id}
                      </td>

                      <td style={styles.td}>
                        {recommendation.full_name || "Guest"}
                      </td>

                      <td style={styles.td}>
                        {recommendation.location_name ||
                          "Unknown"}
                      </td>

                      <td style={styles.td}>
                        <strong>
                          {recommendation.crop_name}
                        </strong>
                      </td>

                      <td style={styles.td}>
                        <div style={styles.scoreWrapper}>
                          <div style={styles.scoreBar}>
                            <div
                              style={{
                                ...styles.scoreFill,
                                width: `${recommendation.compatibility_score}%`,
                              }}
                            />
                          </div>

                          <span style={styles.scoreText}>
                            {recommendation.compatibility_score}%
                          </span>
                        </div>
                      </td>

                      <td style={styles.td}>
                        <span
                          style={getStatusStyle(
                            recommendation.compatibility_level
                          )}
                        >
                          {
                            recommendation.compatibility_level
                          }
                        </span>
                      </td>

                      <td style={styles.td}>
                        {new Date(
                          recommendation.created_at
                        ).toLocaleDateString()}
                      </td>
                    </tr>
                  )
                )
              )}
            </tbody>
          </table>
        </div>

        {!loading && (
          <p style={styles.recordCount}>
            Showing {filteredRecommendations.length} of{" "}
            {recommendations.length} recommendation records
          </p>
        )}
      </section>

      {/* Engine Information */}
      <section style={styles.infoSection}>
        <h2 style={styles.infoTitle}>
          Compatibility Engine
        </h2>

        <p style={styles.infoText}>
          Recommendations are calculated using the agricultural
          requirements stored in the system. The engine evaluates
          soil, water, sunlight, environment, weather, planting
          season, and location suitability to determine how
          compatible a crop is with the user's selected conditions.
        </p>

        <p style={styles.infoText}>
          Administrators manage the underlying crop, requirement,
          location, and planting-calendar data. These datasets
          provide the information used by the recommendation engine.
        </p>
      </section>
    </main>
  );
}

function getStatusStyle(status) {
  if (status === "Highly Suitable") {
    return {
      ...styles.statusBadge,
      backgroundColor: "#e8f5e9",
      color: "#1f5134",
    };
  }

  if (status === "Moderately Suitable") {
    return {
      ...styles.statusBadge,
      backgroundColor: "#fff7e6",
      color: "#9a6700",
    };
  }

  return {
    ...styles.statusBadge,
    backgroundColor: "#fdecec",
    color: "#a33a3a",
  };
}

const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f5f7f5",
    padding: "40px",
    color: "#1f2937",
    boxSizing: "border-box",
  },

  header: {
    marginBottom: "30px",
  },

  title: {
    margin: 0,
    fontSize: "32px",
    fontWeight: "700",
  },

  subtitle: {
    marginTop: "8px",
    color: "#6b7280",
  },

  summaryCards: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
    marginBottom: "25px",
  },

  summaryCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "22px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },

  summaryLabel: {
    margin: 0,
    color: "#6b7280",
    fontSize: "14px",
  },

  summaryNumber: {
    margin: "8px 0",
    fontSize: "25px",
    color: "#1f5134",
  },

  summaryDescription: {
    margin: 0,
    color: "#9ca3af",
    fontSize: "13px",
    lineHeight: "1.5",
  },

  tableContainer: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "25px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },

  tableHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    gap: "20px",
  },

  sectionTitle: {
    margin: 0,
  },

  tableDescription: {
    margin: "6px 0 0",
    color: "#6b7280",
    fontSize: "13px",
  },

  search: {
    padding: "10px 14px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    outline: "none",
    width: "220px",
  },

  tableWrapper: {
    overflowX: "auto",
  },

  table: {
    width: "100%",
    borderCollapse: "collapse",
  },

  th: {
    textAlign: "left",
    padding: "14px",
    backgroundColor: "#f3f6f3",
    borderBottom: "1px solid #e5e7eb",
    fontSize: "14px",
    whiteSpace: "nowrap",
  },

  td: {
    padding: "14px",
    borderBottom: "1px solid #e5e7eb",
    fontSize: "14px",
  },

  scoreWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: "160px",
  },

  scoreBar: {
    width: "90px",
    height: "8px",
    backgroundColor: "#e5e7eb",
    borderRadius: "10px",
    overflow: "hidden",
  },

  scoreFill: {
    height: "100%",
    backgroundColor: "#1f5134",
    borderRadius: "10px",
  },

  scoreText: {
    fontWeight: "600",
    fontSize: "13px",
  },

  statusBadge: {
    padding: "5px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    whiteSpace: "nowrap",
  },

  emptyMessage: {
    padding: "30px",
    textAlign: "center",
    color: "#6b7280",
  },

  recordCount: {
    margin: "15px 0 0",
    color: "#6b7280",
    fontSize: "13px",
  },

  infoSection: {
    marginTop: "25px",
    backgroundColor: "#eef7f0",
    borderRadius: "12px",
    padding: "25px",
  },

  infoTitle: {
    marginTop: 0,
    color: "#1f5134",
  },

  infoText: {
    color: "#4b5563",
    lineHeight: "1.6",
    fontSize: "14px",
  },
};